config/routes.rb
Rails.application.routes.draw do
  resources :categories
  authenticated :user, ->(user){user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: "admin#show_post", as: 'admin_post'
  end

  get 'search', to:'search#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :after_signup

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, inverse_of: :address
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :country, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post,counter_cache: true
  belongs_to :user
  has_rich_text :body

  after_create_commit :notify_recepient
  before_destroy :cleanup_notifications
  has_noticed_notifications model_name: 'notification'

  private
  def notify_recepient
    return if post.user == user
    CommentNotification.with(comment: self, post: post).deliver_later(post.user)
  end

  def cleanup_notifications
   notifications_as_comment.destroy_all
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    #validate if title. description is empty
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :body, presence: true
    belongs_to :user
    #if delete post delete all comments
    has_many :comments, dependent: :destroy
    has_rich_text :body
    belongs_to :category
    
    has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

    has_noticed_notifications model_name: 'Notification'
    has_many :notifications, through: :user

    friendly_id :title, use: %i[slugged history finders]

    def should_generate_new_friendly_id?
        title_changed? || slug.blank?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #delete posts and comments when user is delete     
         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :notifications, as: :recipient, dependent: :destroy
         
         has_one_attached :avatar
         
         has_one :address, dependent: :destroy, inverse_of: :user, autosave: true
         enum role: [:user, :admin]
         after_initialize :set_default_role, if: :new_record?

# Class level accessor http://apidock.com/rails/Class/cattr_accessor
cattr_accessor :form_steps do
  %w[sign_up set_name set_address find_users]
end

# Instance level accessor http://apidock.com/ruby/Module/attr_accessor
attr_accessor :form_step

def form_step
  @form_step ||= 'sign_up'
end

with_options if: -> { required_for_step?('set_name') } do |step|
  step.validates :first_name, presence: true
  step.validates :last_name, presence: true
end

validates_associated :address, if: -> { required_for_step?('set_address') }

def full_name
  "#{first_name.capitalize unless first_name.nil?} #{last_name.capitalize unless last_name.nil?}"
end

accepts_nested_attributes_for :address, allow_destroy: true
 
def required_for_step?(step)
  # All fields are required if no form step is present
  form_step.nil?

  # All fields from previous steps are required if the
  # step parameter appears before or we are on the current step
  form_steps.index(step.to_s) <= form_steps.index(form_step.to_s)
end

private

   def set_default_role
       self.role ||= :user
   end    

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def posts
    @posts = Post.all.includes(:user)
  end

  def comments
  end

  def users
  end

  def show_post
    @post = Post.includes(:user, comments: [:user, :rich_text_body]).find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:user,:rich_text_body).all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user,:rich_text_body).order(created_at: :desc)
  
    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])

      # If an old id or a numeric id was used to find the record, then
    # the request path will not match the post_path, and we should do
    # a 301 redirect that uses the current friendly id.
    if params[:id] != @post.slug
      return redirect_to @post, :status => :moved_permanently
    end

    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  def profile
    @user.update(views: @user.views + 1)
    @posts = @user.posts.includes(:rich_text_body).order(created_at: :desc)
    @total_views = 0

    @posts.each do |post|
      @total_views += post.views
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class: 'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
<div class="container text-center">
    <p>
    <%= link_to "Admin", admin_path %><%= " > #{
        params[:action].capitalize}" unless params[:action].eql?("index") %>
    </p>
    <div class="btn-group">
    <%= render "admin/link", resource: Post %>
    <%= render "admin/link", resource: Comment %>
    <%= render "admin/link", resource: User %>
    </div>
</div>

app/views/admin/comments.html.erb
<h1 class="text-center">Adminstrator</h1>
<%= render 'admin/nav_links' %>

app/views/admin/index.html.erb
<h1 class="text-center">Adminstrator</h1>
<%= render 'admin/nav_links' %>

app/views/admin/posts.html.erb
<h1 class="text-center">Adminstrator</h1>
<%= render 'admin/nav_links' %>

<table class="table table-dark table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Post</th>
      <th scope="col">Author</th>
      <th scope="col">Comment</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
        <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= link_to post.title.truncate(15), admin_post_path(post) %></td>
        <td><%= post.user.full_name %></td>
        <td><%= pluralize(post.comments.count, "Comment") %></td>
        </tr>
    <% end %>
   </tbody>
</table>

app/views/admin/show_post.html.erb
<h1 class="text-center">Adminstrator</h1>
<%= render 'admin/nav_links' %>

<div class="text-center mt-5">
    <div class="btn-group">
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-warning" %>
     <%= button_to "Delete", @post, method: :delete, data: { confirm: "Are you sure you want to delete ?"}, class:'btn btn-danger' %>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <div class="row mt-1">
            <p>
                <strong>Title:</strong><%= @post.title%>
            </p>
        </div>
    </div>

    <div class="body ms-4">
        <div class="row mt-1">
            <p>
                <strong>Views:</strong><%= @post.views %>
            </p>
        </div>

        <div class="row mt-1">
            <p><strong>Author:</strong>
            <%= "#{@post.user.email} | #{@post.user.full_name} | #{pluralize(@post.user.views, "view")}" %>
            </p>
        </div>
        <div class="row mt-1">
            <p><strong>Body:</strong><%= @post.body %>
        </div>
    </div>
</div>
<div class="card mt-3 mb-4">
  <div class="card-header">
        <div class="row mt-1 ">
        <strong><%= pluralize(@post.comments.count, "comment") %>:</strong>
        </div>
  </div>
 
        <% @post.comments.each do |comment| %>
     
        <div class="row mt-1 card-body ms-3">
            <%= comment.user.full_name %>
            <%= comment.body %>
        </div>
        
        <% end %>
        </div>
  </div>
</div>

app/views/admin/users.html.erb
<h1 class="text-center">Adminstrator</h1>
<%= render 'admin/nav_links' %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>